name: CI-iOS

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-12

    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.3.app

    - name: Build and Test
      run: xcodebuild clean build test -project "Essential Art.xcodeproj" -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13 mini,OS=15.5" ONLY_ACTIVE_ARCH=YES
